# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_auto_20170607_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtools',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
