# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20170607_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtools',
            name='image',
            field=models.ImageField(null=True, upload_to='ToolImages/'),
        ),
    ]
