# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_auto_20170607_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penn_guide_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=256, null=True)),
                ('mapping_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.MappingTools')),
            ],
        ),
    ]
