# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_other_guide_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other_guide_url',
            options={'verbose_name': 'other research guide', 'verbose_name_plural': 'other research guides'},
        ),
        migrations.AlterModelOptions(
            name='penn_guide_url',
            options={'verbose_name': 'penn research guide', 'verbose_name_plural': 'penn research guides'},
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='other_research_guides',
        ),
        migrations.RemoveField(
            model_name='mappingtools',
            name='penn_research_guides',
        ),
    ]
