# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_auto_20170612_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingtools',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image'),
        ),
    ]
