# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_auto_20170612_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userstories',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tools.Page'),
        ),
    ]
